# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:           pretty
relative_permalinks: true

# Setup
title:               Anthony Wiryaman
tagline:
description:         Anthony Wiryaman is a freshman at Northeastern, with a combined major in CS and Business Administration.
url:                 http://anthony.wiryaman.com/
baseurl:             /

author:
  name:           'Anthony Wiryaman'
  url:

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/AWiryaman
