# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:           pretty

# Setup
title:               Anthony Wiryaman
tagline:             
description:         Anthony Wiryaman is a freshman at Northeastern, with a combined major in CS and Business
url:                 http://anthony.wiryaman.com/
baseurl:             /

author:
  name:           'Anthony Wiryaman'
  url:             http://anthony.wiryaman.com/

paginate:         5

# Custom vars
version:          1.0.0

# removed so build would work locally
#github:
#  repo:           https://github.com/AWiryaman/

repository:       AWiryaman/AWiryaman.github.io #Added so build would work locally
